# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SJAspects' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SJAspects

pod "Aspects"

  target 'SJAspectsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SJAspectsUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
